# Generated by Django 6.0.6 on 2026-09-03 12:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_collection_featured_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('02a24084-43e9-44d3-8111-925b4e6acd8a'), primary_key=True, serialize=False),
        ),
    ]
